### ISSUE TITLE
Change all DPS Images from `vanilla:3.1.4` to newest

### ISSUE THREAD

**Issue by ranchodeluxe** [Earth-Information-System/fireatlas#104]
Some caveats:
* is `maap-py` not in the newest image?
* is the image clean so I can install what I want and just use pip or is there conda interference?
* does the `scalene` stuff work with it?

**Comment by ranchodeluxe** [comment]
this should also include not just be the DPS algorithms but also the GH Actions DPS image runners

**Comment by zebbecker** [comment]
Completed in #159. Need to release again for updates to go into production, though.

**Comment by zebbecker** [comment]
Released in version 1.2.4
