### ISSUE TITLE
Archive data no longer output through  new API schema 

### ISSUE THREAD

**Issue by mccabete** [Earth-Information-System/fireatlas#124]
The new API Schema gets red of a lot of the clutter around different region names (yay!). Right not it's unclear how/if archival data can be distributed.

Whereas before we had years 2018-2021 in collections with *_archive* in the name, and contrasted that with layers that ended *_nrt*, now we "just" have the layers with data from this year. Can we still distribute the "archival" data?

**Comment by ranchodeluxe** [comment]
I was just about to ticket this! Thank you

With recent changes in the last 24 hours (LF layers are ingesting and very soon they will have the correct name suffixed with `_nrt`) we are now back in alignment with the docs except for the `_archive` table. Once I get the archive table back the docs seem to only need additional information about filtering on the new `region` column name (ticketed in #123) to get at the region you want

To address the archival table we have a couple options here:

* we build up a new archive using Zeb's newest runs for 2018-2024 
* I try to recover the table from an RDS backup and load it manually

I will get to this after I work on some other projects

**Comment by ranchodeluxe** [comment]
Okie dokie, the archive is back online 🥳 

<img width="1786" alt="Screen Shot 2024-08-07 at 9 51 26 AM" src="https://github.com/user-attachments/assets/e4db105d-0dfb-4389-b6be-e0d33a79790c">
