### ISSUE TITLE
Accessing 2020-2023 V3 data from EIS bucket

### ISSUE THREAD

**Issue by mccabete** [Earth-Information-System/fireatlas#137]
@lisamr Has requested the 2020-2023 V3 Feds data as it is generated. Lisa is interested in CA for benchmarking reasons. Would be useful to connect to the EIS bucket.  Already generated the data, but we need to figure out how best to pass it to Lisa without the API.  @zebbecker has generated that data.

**Comment by zebbecker** [comment]
CONUS-wide data generated with v3 is available for 2018-2023 on MAAP at `shared-buckets/gsfc_landslides/FEDSoutput-v3/` as `ArchiveCONUS2018/` etc. Although, do note that I have not done much QC/QA on that- it only finished running quite recently. 

The question now is creating an easy way for @lisamr to download that data from our cloud.

**Comment by zebbecker** [comment]
What I ended up doing: from MAAP ADE: right click on file you want to share and choose "Get Presigned s3 URL". Gives you a link that anyone can use for 24 hours, 1 week, or 30 days.
