### ISSUE TITLE
DPS moving to a new version, all jobs will need to be re-registered

### ISSUE THREAD

**Issue by mccabete** [Earth-Information-System/fireatlas#149]
This is in reference to the announcement by Sujen on [slack.](https://esa-nasa-maap.slack.com/archives/C01308ZHELF/p1726696724095219). Date TBD, but will involve re-registration of algorithms and a switch to mini-conda in the image. As folks with a custom image, this may be an issue.

**Comment by zebbecker** [comment]
Completed!

**Comment by mccabete** [comment]
Huzzah!!!
