### ISSUE TITLE
Move website to fireatlas repo

### ISSUE THREAD

**Issue by mccabete** [Earth-Information-System/fireatlas#152]
@zebbecker  Will you fully move the github.ios to only reference documents in this repo? This should really be run out of this repo (because it's everyone's work), and it's annoying to do a full fork to do  quick commit edits. There are still references to your repo.

**Comment by mccabete** [comment]
Like here https://github.com/Earth-Information-System/fireatlas/blob/conus-dps/_quarto.yml#L25

**Comment by zebbecker** [comment]
Good catch, thank you! Fixed.
