### ISSUE TITLE
Add Boreal V2 and V3  Cron Jobs

### ISSUE THREAD

**Issue by eorland** [Earth-Information-System/fireatlas#19]
While development + benchmarking on v3 continues, I'm hoping that we can provide the data from @mccabete's recurring Boreal runs as a collection on the API. @ranchodeluxe and I have been talking about how much of a lift it may be. This is an ongoing discussion at the moment, but I am hoping that this helps provide some interim information on what is happening in Canada right now (and what may continue to be an issue this summer). Will update this as progress continues.

**Comment by ranchodeluxe** [comment]
closing with additions of https://github.com/Earth-Information-System/fireatlas/pull/13 (will monitor outputs)
