### ISSUE TITLE
Largefire NRT perimeter API data stopped in April 

### ISSUE THREAD

**Issue by mccabete** [Earth-Information-System/fireatlas#58]
The data from the [API](https://firenrt.delta-backend.com) feature collection `public.eis_fire_lf_perimeter_nrt`, stoped providing new data after April 2024-04-07T12:00:00+00:00. Is there something wrong with the API ingest script? 

@ranchodeluxe

**Comment by ranchodeluxe** [comment]
The ingest seems to be working fine I see data for today (note the `sortby` and other query parameters)

https://firenrt.delta-backend.com/collections/public.eis_fire_snapshot_perimeter_nrt/items?limit=1000&sortby=-t&f=json

<img width="1273" alt="Screen Shot 2024-06-12 at 10 57 01 AM" src="https://github.com/Earth-Information-System/fireatlas/assets/208859/1512c478-5836-4080-81e4-3070a0a8e1c7">

**Comment by ranchodeluxe** [comment]
Though it is strange all those old timesteps are in there. The way to double check this is refer to the latest snapshot data in the bucket and do some checks but I'm guess the timestep column in there matches up. 

The v2 legacy stuff decides `t` based on this:
`"SELECT n_pixels, n_newpixels, farea, fperim, flinelen, duration, pixden, meanFRP, isactive, t_ed as t, fireID from perimeter",`

**Comment by mccabete** [comment]
I am talking specifically about the largefire features. `public.eis_fire_lf_perimeter_nrt`

**Comment by ranchodeluxe** [comment]
oh, yeah, sorry 😞 missed that `_lf_` business. yeah, looks like that legacy job is not running 👍 good catch

**Comment by mccabete** [comment]
Full catch points go to @averyfratto!

**Comment by ranchodeluxe** [comment]
This is back online. Please confirm on your end @mccabete and close this if needed

<img width="1123" alt="Screen Shot 2024-06-18 at 5 11 46 AM" src="https://github.com/Earth-Information-System/fireatlas/assets/208859/08a92b73-f8cf-40ca-96c0-ef5ee8efcf24">
