### ISSUE TITLE
v3 not overriding settings with env vars from .env

### ISSUE THREAD

**Issue by zebbecker** [Earth-Information-System/fireatlas#80]
When v3 runs, the pydantic settings module looks for a .env file to load run-specific settings such as FIRE_SOURCE from. The desired behavior is that any env vars set in that file should override the values set in `FireConsts.py`. However, @ranchodeluxe and I paired on this yesterday and confirmed that it appears this is not currently happening in v3. 

It seems that we are using an old syntax to set the [model config](https://github.com/Earth-Information-System/fireatlas/blob/90e216d0c47de35e7a7f4f401f2f4f8b781909a9/fireatlas/FireConsts.py#L20-L24). I have a fix for this in [this branch](https://github.com/Earth-Information-System/fireatlas/tree/zb/settings-override), but getting this working has led me to another issue with Literal behavior [here](https://github.com/Earth-Information-System/fireatlas/blob/7b54e5f14af88819c5de89cb261536f065e82b10/fireatlas/FireConsts.py#L62-L69). My current workaround allows things to run, but loses some intended functionality. I am currently investigating if there is a way to specify allowable options for EPSG codes as integers without causing an error in pydantic settings. Opening this issue as documentation.

**Comment by ranchodeluxe** [comment]
I might have time later today to pair on this again and timebox to an hour. Using `int` instead of a literal here with validation downstream is a totally fine solution. The first bug here is the big one to get in
