### ISSUE TITLE
Playbook on How to Debug Failing DPS Jobs

### ISSUE THREAD

**Issue by ranchodeluxe** [Earth-Information-System/fireatlas#87]
# Problem
Some of us are better at debugging failing DPS jobs than others. Let's write a playbook doc about steps to debug

**Comment by mccabete** [comment]
Case study in API outage. Problem was related to #93 and was traced back to an outage on the LAADS DAAC side. Now, however, the largefire nrt api is still not updating. My debugging steps were: 


-check input data is there
-check that feds ran successfully, serialization files through today exist
- check if nrt snapshot API is updating

Now I am re-running the conus nrt lf v2 workflow. I am trying to see if there was some sort of failure. 

- Avery queried the data itself. Seems like the largefire data is not up to date.

**Comment by ranchodeluxe** [comment]
first draft is up via #108
