### ISSUE TITLE
QUESTION: Renable SNPP Data Inputs

### ISSUE THREAD

**Issue by ranchodeluxe** [Earth-Information-System/fireatlas#91]
# Question
We removed SNPP data processing inputs b/c they were causing problems. But rumor has it they are back now and better than ever?

**Comment by mccabete** [comment]
Nope, turns out there was anouther outage.

**Comment by mccabete** [comment]
Outage started July 24th, unclear if it will resume providing data.

**Comment by mccabete** [comment]
This website list outages. https://modaps.modaps.eosdis.nasa.gov/services/production/outages_suomi_npp.html

It has the outage as starting July 9th, so it could be the same outage, and it just took a while to be flagged by worldview (where I got the July 24th date).

**Comment by mccabete** [comment]
I am closing this for the time being.
