### ISSUE TITLE
Decide on Gitflow Workflow and Document for Future Us

### ISSUE THREAD

**Issue by ranchodeluxe** [Earth-Information-System/fireatlas#95]
# Problem
This repository (unlike the other VEDA repositories) can decide on what our Gitflow options we want. Currently we create feature branches off `conus-dps` (the default branch) that get merged. But there are other options

# AC
- [ ] Talk about and pic something

**Comment by ranchodeluxe** [comment]
@jsignell is recommending that we merge `conus-dps` to `main` and make `main` the default branch

**Comment by jsignell** [comment]
Oh I was thinking just delete `main` and rename `conus-dps` to `main` 🙈  but your idea is better.

**Comment by zebbecker** [comment]
If we decide on a git flow, I will write it up and add to documentation. 

Current concept: 
- rename conus-dps to main 
- develop features in feature branches directly off of main
- merge feature branches back into main when completed
- any PRs to main will automatically trigger both the normal test suite and `--runslow` integration tests
- to put new features into production, follow the [release workflow](https://github.com/Earth-Information-System/fireatlas/blob/conus-dps/docs/releasing.md) once all needed PRs have been merged into main  

This seems fine to me, but I have less experience with different options than you two do @jsignell @ranchodeluxe . Does this sound good? Or, we can set something up with a dev branch in addition to a main branch, or another option.

**Comment by jsignell** [comment]
This sounds like the standard approach to managing development on a library. So big :+1: from me. One thing that you should definitely consider is branch protection. That lets you control what can get merged to main. For instance you can specify that there has to be a review, or that the tests have to pass.

**Comment by zebbecker** [comment]
Completed in #161
