### ISSUE TITLE
Create PyPi Account for Releases

### ISSUE THREAD

**Issue by ranchodeluxe** [Earth-Information-System/fireatlas#99]
# Problem
We need a pypi account so we can release the fire code and then folks can easily pip install different versions as needed for future us.

# AC
- [ ] @mccabete and @eorland to go to https://pypi.org/account/register/ and create an EIS Fire Atlas account using one of your emails
- [ ] @mccabete or @eorland to then get an API token (https://guidebook.devops.uis.cam.ac.uk/howtos/pypi/) and DM me the username and password so we can use it as a secret in the GH actions

**Comment by mccabete** [comment]
Yes I can do this. I am working on it, may be fully done tomorrow morning.

**Comment by mccabete** [comment]
I promise I am working on this. Might get punted to tomorrow.

**Comment by mccabete** [comment]
Looks like it wasn't a data outage --https://ladsweb.modaps.eosdis.nasa.gov/alerts-and-issues/ . This might have been a server outage? I guess I can't figure out if we can go back and "fix" the hole in the data.

**Comment by mccabete** [comment]
@ranchodeluxe  -- The documentation you sent suggests making a ruleset for protecting the default branch under the assumption that there will be some level of auto-published happening when versions change. Is that something you are advocating for?

**Comment by mccabete** [comment]
Also, I'm assuming you want a token for pipy and test pypi

**Comment by ranchodeluxe** [comment]
> @ranchodeluxe -- The documentation you sent suggests making a ruleset for protecting the default branch under the assumption that there will be some level of auto-published happening when versions change. Is that something you are advocating for?

yes, `conus-dps` or `main` will be protected (currently I think both are)

> Also, I'm assuming you want a token for pipy and test pypi

I don't really need the one for "test" just normal pipy thankyou
